const RecommendationsActionTypes = {
  SUCCESS_FETCH_RECOMMENDATIONS: 'SUCCESS_FETCH_RECOMMENDATIONS',
  FAILURE_FETCH_RECOMMENDATIONS: 'FAILURE_FETCH_RECOMMENDATIONS',
  REMOVE_RECOMMENDATION: 'REMOVE_RECOMMENDATION',
};

export default RecommendationsActionTypes;
