const RecommendationsActionTypes = {
  SUCCESS_FETCH_RECOMMENDATIONS: 'SUCCESS_FETCH_RECOMMENDATIONS',
  FAILURE_FETCH_RECOMMENDATIONS: 'FAILURE_FETCH_RECOMMENDATIONS'
};

export default RecommendationsActionTypes;
